[package]
rust-version.workspace = true
name = "sdkwork-api-kernel-assembly"
edition.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-kernel application HTTP plane."


[lints]
workspace = true
[lib]
name = "sdkwork_api_kernel_assembly"
path = "src/lib.rs"

[dependencies]
axum = "0.8"
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork-agent-server.workspace = true
sdkwork-routes-agent-internal-api.workspace = true
