[package]
rust-version.workspace = true
name = "sdkwork-agent-plugin-core"
version = "0.1.0"
edition = "2021"


[lints]
workspace = true
[lib]
name = "sdkwork_agent_plugin_core"
path = "src/lib.rs"

[features]
test-utils = []

[dependencies]
sdkwork-agent-kernel.workspace = true
dunce = "1"
pep440_rs = "0.7.3"
semver = "1"
serde_json = "1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_JobObjects",
    "Win32_System_Threading",
] }
