[package]
rust-version.workspace = true
name = "sdkwork-kernel-plugin-knowledgebase"
version = "0.1.0"
edition = "2021"


[lints]
workspace = true
[lib]
name = "sdkwork_kernel_plugin_knowledgebase"
path = "src/lib.rs"

[dependencies]
sdkwork-agent-kernel.workspace = true
sdkwork-agent-plugin-core.workspace = true
sdkwork-knowledgebase-contract.workspace = true
